version: "3"
services:
  app:
    container_name: app
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo
      - redis
    volumes:
      - ./:/usr/src/app
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ./data/mongodb:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: aswita
      MONGO_INITDB_ROOT_PASSWORD: aswita
  redis:
    container_name: redis
    image: "redis"
    volumes:
      - ./data/redis:/redis/db
      - ./redis.conf:/data/redis
    ports:
      - "6379:6379"
    expose:
      - "6379"